language: java
jdk:
  - oraclejdk8

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -f it/sample -B -V

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: script
  script: ci/deploy.sh
  on:
    branch:
      - master
      - develop

env:
  global:
  - secure: FExaaOQRDjj0k+aRiCylEqz0w+lW8wgOr6f0z8UQXlBDbY1yjUpv8H6iHgqNiwCBoifpv4mctTiD/qq1PQS71jGx6+lptEvmLijwy1enRIfmw0fvZmSmYWvsnZGCORht3bY4qOHe07bdW7wvTTTVpSIhgYY1awLyv1vUbYc2yljcVbtrSDmUfk8NotZtsIj8FqIHiEGH1o7AsNq+Imf/z0nC0DnJgUxBmWWxzUEJLprzRXjAaBaTqoc3pjw7G6AcB0hCY7GQp+WneB3xFr2DGyG8g0oLHl58nnA0xrPQ3Jdh9kB3r4dNIluzDi2aMexmbhHfs5aF0oMHnA5gKxWbjayEeU+VYkCxf/7dEFBdkSrtH1trj90szxnAxyzqGupM1PK3I2BjJus4x//ATGdHNDchptjnqFhdnkwO7O06nra44irkL7dFVXjiPwsU/Z9LpFdft6Ob63NLr7LeMhj1vVYOGiQNBw22q6pL285IRC/Bp1cdrt5nH9uiqQe4lq03UpBiwSbaQAp+Ad0voX4kai2+bBSxaBUVjfT0FINSPQSLzJPzXUXVpCzetMl9BFhicfSqXCX+9dolLOE1IB3Cr2VPkNyrkAVbH2ovHfgEvUp6Pey/PUbAMUKHLqhhAVsrHYtHTm0dFV1R8r6a2pNsBv42cdmLVGolDgaS/tmbCMo=
  - secure: EAn+6KeIj50Y8I3a9euoJQM+D75nIkxmPaHN668Fi/+z/v/SlSvyjPmC3ICnLb67L+aewvW+z10iUapBkeo3S4QPMwlqOkTTqaKzJx9z67UQOM/iJHxRkHZLHAarNynGi1sDSToLMfDXjzau7AZsC57Xi8WnExJQTfQ4ZXiHRXNu7DlXitN342OK0x6pEsQqFe7Tb+I538ptsKApLA3L6Rz/iqrZ7hsiZpXrQF/Seq8xeNpB1hWUD6wMQm66pQ3bioaq2JZuzDrbsHm8L8RMawyW9UXhAsxcpFAhVEKSerxaVtVkjdaI1BkmTms9RK938s4iC54vo5dLOUE7XZB0sZBcK8mq0PSMwCKKA1asdgbzym57+35NkC1x6SNygMTub6AgSc4N1Dq7T+FubKZxEE3nFv2NsS6v1Viw0Ike/Z5DxMtw8a1ughpUcsnGgHsJdlUeRrKG8eoVCdYkzAvaHv37H9bL5nQgJV8CNkkdHjQ7QtNnmoZoqxatmVjuHtWN1qYcXwOeQ3ZD1p7x+zMLbe1PWVOuNDnp5Iv2T5pQrkDPnjvZ8mAfGJqk+f+gaZL10QRVgUUHTOevVkjRomFyIgNcwfNyXSpA1Ya4Bm1V4OonD9TGIiVVPxN7ec9/IUFnCxO9uW8Avrkd52WTyTLcdS/qKjcohVa6jhWiEDuQhN8=
  - secure: IFG+Y7BqFe+KmnATImqttn2V2Ja8L2JEiRiASr1ce+C0Kd+HN2LULUhkBIQP0UFxdk0PeyAtD22d+WfsdyFdbsKWTnvD8HLytvB4Okc/t9U3zmz8fFr3zfKTaWQ9y4uZ8Ml+nBChbUqxpdgXUs9MbMWn1PJ+ZQOYnEo62MW1Dyn2imRNGSH8DX110018qeDBNjfkVAvE7RMt+9O5arr0xYwZ/ebAFzd9Hqwf/YskZTdFO45lPNGZgHblcq/QiTRdQCze6yet5CUmpPejKlxzQJeDLn41nGAEsjpVQwSB8CmHfbKbfiA0uJBnT0kpV39virXIVq01h0rqCOJsGWOOf2FuWLCI6QEbm+iROVATOZyHtD5NAd+3XZ0O7PPWP6HYNA7m1qYdAvinqMElE3ROvrGRKslJL+2gdpveqrjMW3qvd6dXkK7PX7gkaOHJ93uGfhtXjhPKr6oYwsuY4/tKBZmtj8APvEyq8Mm26LQxl3pWGA43uori4wBGCQ3UD4UuI0HeJlWo7zu7ww/bOADBRjlWJx1ZWIz02U/1q6eSAlZTUVnc5W/4VQqpLcfaF0ZvaTe3nGqrh/uIAb/6/FxyNI0HCVoSrcHyGsEdhsnM9h7AKoj1Klv1zKs7UJzvgye5aVlmlsA+kxYipgPwMbDxmg02JOwzNWw2yXi199CmxgU=
  - secure: tdV/Yn8hgmBbNsYgQ2adJXgAea9CqvTOMRDQbCxlFz/nhGBhYVcGxwhoHGDTQGMiqj/OKYqQJTGGo7KHSw0lmtYtQ3Rox67VLmqb4klmaiaYTncpIOw96eY/hUwQSemgOvcU/ST6QKc+rQu7LtsLauy9e1RD7dFgJqQZwyjYBOysLclwFfTnhDzsGbQhYSts4SVBfOYs3mh+ApR5k4cYeDJQ18iQFGb/o6JuUIjTxz+TcuOb7Y6bKHGy+7jclXpt5KzA8Cmbyc+nrYLFclTHzjDpMFv7yDu9LiEk3DW1bqMhLO8WbMOiW2mnFWtBi9KuuPj5qeaeWSuuLYEf8fy1nV8WWtQy2Dxku1idEfA1koYI+70KjBxPLji/ZG6XRi0Pf0jyuXVJpVjiYmo1KYEhBt8AMfJOgXwDHBXSJTTWx85lTkxOpSbcKYMlbyxgBpi6KjmpYC90BHvNE4YxBvimE+we9GG7Jpox0IiQdNv8Gm7Ta4W1sbMoZaH5994WR2JPwYHuyXJPL3eRaxs+a3wtkBfVVnzAS39R4qrC6Ayci+RCju26hRpG6gnku2eWR4+H0bVD9gP8r6rREx4MIEUajdvJ8yqHQyC3vz0rp7rWGVPeCSvp6kUsNI6OqDrYr4hv/bAUW1xnlw+FbeeOM8AxOEaHjbTF0mms7ka9RCUx8Jk=
